name: familyapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/dog_room/dog/
    - assets/dog_room/room/
    - assets/dog_room/furniture/

  fonts:
    - family: PalaceScript
      fonts:
        - asset: assets/fonts/Palace_script.ttf
